### ISSUE TITLE
question regarding the gmsv_gac module shipped with this repo

### ISSUE THREAD

**Issue by VaasKahnGrim** [GlorifiedPig/g-ac#10]
basically I was wondering if you by chance could upload the non compiled version of the module to the repo aswell too. That way people can review it before simply putting it on their server without knowing what it does.

**Comment by Vadmeme** [comment]
It does nothing, this is DRM free just delete it or open it in ida

**Comment by Vadmeme** [comment]
If you really care it adds a RunStringG function that function does the following:

1. Base64 decode
2. XOR with key 0x1C
3. Base64 decode again
4. Execute code via lua_loadbuffer

**Comment by VaasKahnGrim** [comment]
Ah, I see. well thanks for the info anyways :)

**Comment by GlorifiedPig** [comment]
Download the latest release — the DRM binary modules have been removed and the performance slightly increased
