### ISSUE TITLE
/addons/gac/lua/glorifiedanticheat/modules/antiantiaim/sv_gac_antiantiaim.lua

### ISSUE THREAD

**Issue by genrihx2** [GlorifiedPig/g-ac#14]
[ERROR] GAC_hG7g37pnE_973:35: attempt to call upvalue 'GM_StartCommand' (a nil value)
1. unknown - GAC_hG7g37pnE_973:35

**Comment by Zulbem** [comment]
Just remove the folder for now. It works fine without it.

**Comment by genrihx2** [comment]
thank   Zulbem  works
