### ISSUE TITLE
don't run this

### ISSUE THREAD

**Issue by brightersun99** [GlorifiedPig/g-ac#21]
half the anti-cheat is obfustacated, this could be a backdoor and there's no way to verify its contents

**Comment by GlorifiedPig** [comment]
as if you can't simply ..? unobfuscate it yourself ?

**Comment by brightersun99** [comment]
and you expect server owners to do that? no one is going to use your crappy backdoor, skid

**Comment by brightersun99** [comment]
backdooring is so 2016

**Comment by GlorifiedPig** [comment]
Ok

**Comment by nodgear** [comment]
> half the anti-cheat is obfustacated, this could be a backdoor and there's no way to verify its contents

What to expect from someone that doesn't know the difference between obfuscation and backdooring
