### ISSUE TITLE
Umm excuse me, this is leaked

### ISSUE THREAD

**Issue by RadioactvePixels** [GlorifiedPig/g-ac#7]
Why would I download this one, and not the leaked one?

**Comment by Aws0mee** [comment]
0-0

**Comment by Aws0mee** [comment]
nigger am I right

**Comment by RadioactvePixels** [comment]
> 
> 
> 0-0

I know right!

**Comment by Yogpod** [comment]
this one is unobf-drmfree
the one that got leaked was obf-drmfree

**Comment by Aws0mee** [comment]
<@210828786462228480>

**Comment by RadioactvePixels** [comment]
> 
> 
> this one is unobf-drmfree
> the one that got leaked was obf-drmfree

Erm. It was a joke.

**Comment by Vadmeme** [comment]
this just proves the leak was real, all it took was 1 leak and entire ac shut down

**Comment by RadioactvePixels** [comment]
<@210828786462228480>

**Comment by Aws0mee** [comment]
<@647722485332181002>

**Comment by RadioactvePixels** [comment]
<@210828786462228480>

**Comment by RadioactvePixels** [comment]
<@647722485332181002>

**Comment by Aws0mee** [comment]
bring gac back plz

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@647722485332181002> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
<@583088177569464330> Lol, imagine getting an anti-cheat leaked.

**Comment by RadioactvePixels** [comment]
lmao
